### ISSUE TITLE
Redundant getters/setters

### ISSUE THREAD

**Issue by k0ral** [gtk2hs/webkit#10]
For instance: the `webViewUri` attribute can be read using `System.Glib.Attributes.get`, why is there another function `webViewGetUri` to do the same job ?
A lot of attributes in the current webkit API have these seemingly redundant getters/setters, wouldn't it be simpler to get rid of them ?

**Comment by k0ral** [comment]
In #9, @hamishmack explains that the direct getter/setter doesn't suffer the overhead of looking up the property by name, which justifies the existence of some redundant getters/setters, but not all.
The issue remains for attributes that aren't properties, e.g.:

```
webViewViewSourceMode :: WebViewClass self => Attr self Bool
webViewViewSourceMode = newAttr
  webViewGetViewSourceMode
  webViewSetViewSourceMode
```

In this case, there should be no overhead, so there may be no point in exporting the redundant getter/setter.

**Comment by hamishmack** [comment]
We should deprecate the webViewGetViewSourceMode and webViewSetViewSourceMode and then stop exporting them.  It would be a big job to do all of gtk2hs, but we might be able to automate some of it.  We could write some code to find when `xGetY`, `xSetY` and `xY` exist in the the same module and make the appropriate changes to deprecate `xGetY` and `xSetY` and put an `#ifdef` around their export.

**Comment by hamishmack** [comment]
Seems little point fixing this now gi-webkit and gi-webkit2 exist.
