### ISSUE TITLE
Add RequestAnimationFrameCallback and Window (requestAnimationFrame)

### ISSUE THREAD

**Issue by Mikolaj** [gtk2hs/webkit#14]
See https://github.com/ghcjs/ghcjs-dom/issues/35#issuecomment-170245044 for details.

**Comment by Mikolaj** [comment]
I suppose this is fixed, since I no longer get the compilation error. Thanks!

**Comment by Mikolaj** [comment]
Unfortunately, I was wrong, I'm still getting

```
[ 98 of 125] Compiling Game.LambdaHack.Client.UI.Frontend.Dom ( Game/LambdaHack/Client/UI/Frontend/Dom.hs, dist/build/Game/LambdaHack/Client/UI/Frontend/Dom.o )

Game/LambdaHack/Client/UI/Frontend/Dom.hs:36:26: error:
    Module ‘GHCJS.DOM.Window’ does not export ‘requestAnimationFrame’
```

with webkitgtk3-0.14.2.0 and ghcjs-dom-webkit-0.3.1.0.

**Comment by Mikolaj** [comment]
I've tried adding

```
requestAnimationFrame ::
                      (MonadIO m, WindowClass self,
                       RequestAnimationFrameCallbackClass callback) =>
                        self -> Maybe callback -> m Int
requestAnimationFrame self callback
  = liftIO
      (fromIntegral <$>
         ({# call webkit_dom_dom_window_request_animation_frame #}
            (toWindow self)
            (maybe (RequestAnimationFrameCallback nullForeignPtr)
               toRequestAnimationFrameCallback
               callback)))
 
cancelAnimationFrame ::
                     (MonadIO m, WindowClass self) => self -> Int -> m ()
cancelAnimationFrame self id
  = liftIO
      ({# call webkit_dom_dom_window_cancel_animation_frame #}
         (toWindow self)
         (fromIntegral id))
```

to https://github.com/gtk2hs/webkit/blob/master/Graphics/UI/Gtk/WebKit/DOM/Window.chs, but with no luck, because `webkit_dom_dom_window_cancel_animation_frame` is nowhere to be found and I can't even find any mention of it on the web. What am I missing?

**Comment by Mikolaj** [comment]
As far as I can see now, the `webkit_dom_dom_window_cancel_animation_frame` is just wrongly invented by `domconv-webkit` (whereas `webkit_dom_dom_window_cancel_animation_frame` is possibly correct). Instead it should probably somehow call `dom/Document.cpp:int Document::requestAnimationFrame(PassRefPtr<RequestAnimationFrameCallback> callback)` though perhaps it needs to be wrapped in some `dom_dom` first --- I have no clue. BTW, the good news is, the call is identical in webkitgtk-2.4.11.tar.xz (Webkit1 API) and webkitgtk-2.14.0.tar.xz (Webkit2 API).

Help?

Or is it all obsolete anyway, because of https://hackage.haskell.org/package/gi-webkit?

**Comment by hamishmack** [comment]
> Or is it all obsolete anyway, because of https://hackage.haskell.org/package/gi-webkit?

Sort of.  It is worth checking out what ghcjs-dom-jsaddle does.  It talks to JavaScriptCore using jsaddle and works with gi-webkit.  It is generated from the same IDL files and might have similar issues.  I might have time this weekend to investigate.

**Comment by Mikolaj** [comment]
`jsaddle-dom` does call requestAnimationFrame directly, `ENABLE_REQUEST_ANIMATION_FRAME` is on, and there are no apparent issues marked in the code (I haven't tested it):

```
src/JSDOM/Generated/Window.hs:-- | <https://developer.mozilla.org/en-US/docs/Web/API/Window.requestAnimationFrame Mozilla Window.requestAnimationFrame documentation> 
src/JSDOM/Generated/Window.hs:requestAnimationFrame ::
src/JSDOM/Generated/Window.hs-                      (MonadDOM m) =>
src/JSDOM/Generated/Window.hs:                        Window -> Maybe RequestAnimationFrameCallback -> m Int
src/JSDOM/Generated/Window.hs:requestAnimationFrame self callback
src/JSDOM/Generated/Window.hs-  = liftDOM
src/JSDOM/Generated/Window.hs-      (round <$>
src/JSDOM/Generated/Window.hs:         ((self ^. jsf "requestAnimationFrame" [toJSVal callback]) >>=
src/JSDOM/Generated/Window.hs-            valToNumber))
```

**Comment by Mikolaj** [comment]
I've tested my program in GHC with the version of ghcjs-dom using jsaddle-dom and it works, though it required quite a few changes to the code (in particular, `postGUISync` is no longer in IO, though it can be worked around):  https://github.com/LambdaHack/LambdaHack/commit/3b4c0700658eb7880c7240540ad81e3c81c0d9a2

I've then tested the same modified code with ghcjs using jsaddle-dom and ghcjs using jsffi and both compile fine and work the same. The changed code doesn't work with ghcjs-dom-webkit any more, unsurprisingly, while previously the only error was the one about `requestAnimationFrame`:

```
Game/LambdaHack/Client/UI/Frontend/Dom.hs:33:46: error:
    Module ‘GHCJS.DOM.Types’ does not export ‘DOM’

Game/LambdaHack/Client/UI/Frontend/Dom.hs:33:51: error:
    Module ‘GHCJS.DOM.Types’ does not export ‘DOMContext’

Game/LambdaHack/Client/UI/Frontend/Dom.hs:34:25: error:
    Module ‘GHCJS.DOM.Types’ does not export ‘askDOM’

Game/LambdaHack/Client/UI/Frontend/Dom.hs:34:55: error:
    Module ‘GHCJS.DOM.Types’ does not export ‘runDOM’

Game/LambdaHack/Client/UI/Frontend/Dom.hs:37:26: error:
    Module ‘GHCJS.DOM.Window’ does not export ‘requestAnimationFrame’
```

The jsaddle version runs terribly slowly, much slower than the same JS (via ghcjs) in Chrome. It may have something to do with it apparently using Java, because it displays at startup

```
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

Or perhaps requestAnimationFrame works wrongly, though the calls to it compile fine. Or perhaps V8 is just so much better.

**Comment by Mikolaj** [comment]
I've ported my code, again, to jsaddle-dom 0.4.0.1: https://github.com/LambdaHack/LambdaHack/commit/7e1618f829b97a14fe3be89120ab01abcb29bda9

* the ghcjs-compiled programs with ghcjs-dom-jsaddle and with ghcjs-dom-jsffi run in Chrome with the same speed on code that doesn't use DOM at all

* also, when run with `node`, they are only a tiny bit faster than with Chrome and there's no difference in speed between them

* in Chrome, the ghcjs-compiled program with ghcjs-dom-jsaddle is almost 3 times slower than the one with ghcjs-dom-jsffi on code that spends a quarter of its runtime updating text and colours in a table in the browser window

* the ghc-compiled (not ghcjs!) program with ghcjs-dom-jsaddle works terribly slowly, completely ignoring requestAnimationFrame, and so refreshing the browser window after each table cell modification 

*  the ghc-compiled (not ghcjs!) program with ghcjs-dom-jsaddle stops showing any new things (and never responds to keypresses) after the first call that modifies all table cells finishes, but the browser (but possibly also the Haskell executable) uses lots of CPU (at this stage, the browser spends a quarter of its elapsed runtime calling things from jsaddle.js, half of the runtime on something related to 'onmessage', and is idle for the remaining quarter); when the Haskell program is killed, the browser idles up; I think with ghcjs-dom-jsaddle 0.3.1.0 it worked as slowly, but responded correctly

* there is no more mention of Java at the server startup and generally no server messages, except "LambdaHack: CloseRequest 1001", etc. at appropriate moments

* there is a mild stack space leak (200K stack is not enough) in the Haskell program not seen when compiled with version ghcjs-dom-jsaddle 0.3.1.0 and with ghcjs-dom-webkit

**Comment by hamishmack** [comment]
> the ghc-compiled program with ghcjs-dom-jsaddle works on code that modifies the browser display terribly slowly, completely ignoring requestAnimationFrame, and so refreshing the browser window after each table cell modification

This might happen if there is a synchronous operation in there your update code (or in some part of jsaddle or jsaddle-dom where it does not belong).  If you debug [jsaddle.js](https://github.com/ghcjs/jsaddle/blob/master/data/jsaddle.js) in the browser you should be able to work out what the synchronous operation is.  Perhaps add some logging to jsaddle.js.

You will see that when a message arrives jsaddle.js [first loops through all the async commands](https://github.com/ghcjs/jsaddle/blob/master/data/jsaddle.js#L27) and then it does [the one synchronous operation in the batch](https://github.com/ghcjs/jsaddle/blob/master/data/jsaddle.js#L123) and sends the result back.   When you are updating DOM stuff you want all the updates to be done in that loop of async commands.

In general you will need to structure you code in such a what that it does not look at the state of the browser while doing these updates.  As soon as you do that you incur the penalty of a round trip and the browser thinks you are done updating the dom and redraws slowing things down even more.

I have not done a lot of testing yet and there might be places in jsaddle-dom where synchronous operations are sneaking in where they should not be.

**Comment by hamishmack** [comment]
> completely ignoring requestAnimationFrame

We need to think about how to deal with this.  We will need to add support to jsaddle.js.  It will be a little tricky.  It could work something like this though:

``` Haskell
syncWithAnimationFrame $ do
    -- normal ghcjs-dom code here but nothing sync stuff allowed
```

Once the block finishes it would be sent to the jsaddle.js in a special sort of batch to be run in the requestAnimationFrame call back.

**Comment by Mikolaj** [comment]
> If you debug jsaddle.js in the browser you should be able to work out what the synchronous operation is.

Indeed, I've found two culprits, `getStyle` and `removeProperty'. I eliminated them (pushed the commits) and now the whole DOM update fits in a single send, which speeds up the ghc jsaddle version a lot and does not affect the jsffi version (at least not beyond the quite large measurement error). I will now look at the other problems.

BTW, pusing `getStyle` out of the `requestAnimationFrame` callback has slowed down the ghcjs jsaddle version from 0.84 FPS to 0.55 FPS. The overhead compared to ghcjs with jsffi (2.25 FPS) seems to have something to do with communication or threads, because there's a lot of onGlobalMessage and threadSlice in the portions that take the most time (and they are all outside of the `requestAnimationFrame` callback). Anyway, that doesn't bother me, because I will use jsffi-dom for ghcjs. What I'm interested in is getting the ghc version with ghcjs-dom (jsaddle or webkit) to work and making it as fast as the other frontends I have (e.g., 70 FPS with the gtk frontend).

**Comment by hamishmack** [comment]
@Mikolaj I have added this https://github.com/ghcjs/ghcjs-dom/issues/53 which might allow you to use unsafeGetStyle and removeProperty_ to avoid synchronous commands.

**Comment by Mikolaj** [comment]
I've narrowed down the problem with ghc-compiled jsaddle code "only showing the first frame". In fact, as long as I press no keys, it shows some more frames as well, but very slowly: at the speed of 0.06 FPS. Browser is idle almost all the time; the overhead is in the native binary.

I've profiled the binary and the results, after drawing 5 frames for over 1 minute, are as follows (my code seems to take less than 5% of overall mutator time and less than half memory):

```
COST CENTRE       MODULE                                  %time %alloc

tryReadTChan      Control.Concurrent.STM.TChan             89.2    0.9
string            Data.Aeson.Encoding.Builder               1.8   11.7
genericToEncoding Data.Aeson.Types.ToJSON                   1.5   20.8
int64             Data.Aeson.Encoding.Internal              1.1    8.8
pair              Data.Aeson.Encoding.Internal              0.7   12.0
sendLazyCommand   Language.Javascript.JSaddle.WebSockets    0.4    2.5
jsaddleOr         Language.Javascript.JSaddle.WebSockets    0.4    1.4
findPosTry        Game.LambdaHack.Common.Level              0.3    5.3
jstring_          Data.Aeson.Parser.Internal                0.2    1.1
objCallAsFunction Language.Javascript.JSaddle.Object        0.2    2.6
writeTChan        Control.Concurrent.STM.TChan              0.2    1.1
maskPayload       Network.WebSockets.Hybi13.Mask            0.2    1.9
encodeMessages    Network.WebSockets.Hybi13                 0.2   11.4
text              Data.Aeson.Encoding.Builder               0.2    4.5
withJSString      Language.Javascript.JSaddle.Native        0.1    1.0
encode            Data.Aeson                                0.0    2.2
```

Another problem is that mouse button presses are processed very slowly and erratically and any keypresses are misreported as mouse button presses, that is, handled here

https://github.com/LambdaHack/LambdaHack/blob/master/Game/LambdaHack/Client/UI/Frontend/Dom.hs#L276 

instead of here

https://github.com/LambdaHack/LambdaHack/blob/master/Game/LambdaHack/Client/UI/Frontend/Dom.hs#L154

and here

https://github.com/LambdaHack/LambdaHack/blob/master/Game/LambdaHack/Client/UI/Frontend/Dom.hs#L186

The same code works fine with ghcjs.

**Comment by hamishmack** [comment]
I have added the "_" and "Unchecked" versions of functions to the github version of `jsaddle-dom` (used by ghcjs-dom-jsaddle).  I have also added a `nextAnimationFrame` function (to `jsaddle` and `jsaddle-dom` on github) that you can use to execute code inside the requestAnimationFrame callback.   As soon as it gets to a synchronous command though it will stop and the rest of the commands will be executed as normal (in the websockets callback).

**Comment by hamishmack** [comment]
I think [this](https://github.com/ghcjs/jsaddle/commit/403070b6ade2b67d4e4d985ae9efd3c3ba0cf7e4) might get `tryReadTChan` off the top of your list.

**Comment by hamishmack** [comment]
> keypresses are misreported as mouse button presses

This sounds a lot like the issue where callback functions in the same asynchronous batch all got the same ID.  It should have been fixed in the latest github version.  [This was the original fix](https://github.com/ghcjs/jsaddle/commit/7d65af9681bba8c93f1df23e1aad761c9e2b815c).  But I have since moved it [here](https://github.com/ghcjs/jsaddle/blob/master/data/jsaddle.js#L66).  Without that function wrapping the block of code all the callbacks in the batch end up sending the same `nFunction` value back over WebSockets.

**Comment by Mikolaj** [comment]
Wow, without change to my code, I got the keys and mouse working perfectly and I've got from 0.06 FPS to 1.75 FPS. Now I managed to profile not a 5 frames run, but a 100 frames run before it ate all my memory:

```
string             Data.Aeson.Encoding.Builder              21.6   15.5
genericToEncoding  Data.Aeson.Types.ToJSON                  19.5   27.2
int64              Data.Aeson.Encoding.Internal             14.8   11.5
pair               Data.Aeson.Encoding.Internal              8.5   15.8
sendLazyCommand    Language.Javascript.JSaddle.WebSockets    2.8    1.5
objCallAsFunction  Language.Javascript.JSaddle.Object        2.6    3.3
jsaddleOr          Language.Javascript.JSaddle.WebSockets    2.1    1.5
text               Data.Aeson.Encoding.Builder               2.1    6.0
retagEncoding      Data.Aeson.Encoding.Internal              1.9    0.0
getCacheBfsAndPath Game.LambdaHack.Client.BfsM               1.7    0.4
writeTChan         Control.Concurrent.STM.TChan              1.7    1.2
tryReadTChan       Control.Concurrent.STM.TChan              1.3    0.5
withJSString       Language.Javascript.JSaddle.Native        1.1    1.2
encodeMessages     Network.WebSockets.Hybi13                 0.3    1.5
encode             Data.Aeson                                0.2    1.3
```

I suspect I'm sending full JS commands or tons of data to the browser each frame, while most of the data is constant and could be kept or regenerated on the JS size. The variable data is at most a vector of 80x20 Word32 values per frame; that's just 800 words, around 6Kb. If it could somehow be sent packed, that would be ideal. If it's not packed and if the constant data is sent as well, it's many times larger. And if I'm instead sending 80x20x5 raw serialized JS commands like `setProperty style "background-color" (Just "#D50000") ""`, that's obviously a disaster and even more so if the strings are not memoized in any way.

I haven't tried the 'nextAnimationFrame' yet, but the browser is still idle most of the time, so the main problem is still the communication and most of all the JSON encoding.

**Comment by Mikolaj** [comment]
I've had a look at `nextAnimationFrame` and it may indeed fit the bill, but sadly I will need to start depending on jsaddle-dom instead of ghcjs-dom and also I will need to ifdef this, so that I can keep using the proper `newRequestAnimationFrameCallback` and `requestAnimationFrame_` for jsffi. I guess the ifdefs can't be avoided, because the semantics of `nextAnimationFrame` and `requestAnimationFrame` will always differ, because sync commands affect `nextAnimationFrame`. Anyway, great job, and also with the auto-generation of Unchecked and *_ variants of functions.

**Comment by hamishmack** [comment]
> but sadly I will need to start depending on jsaddle-dom instead of ghcjs-dom and also I will need to ifdef this, so that I can keep using the proper newRequestAnimationFrameCallback and requestAnimationFrame_ for jsffi

I have just updated the ghcjs-dom webkit repo so ghcjs-dom should now have everything I added to jsaddle-dom (including `nextAnimationFrame` and the `Unchecked` and `_` functions).  Please let me know if it looks ok.  If it does I will push it all up to hackage.

**Comment by Mikolaj** [comment]
Thank you. The Unchecked variants alone are a treasure, even just because they reduce code clutter so much. I've compiled and ran all combinations of the flags/libs and it all works fine, except for https://github.com/ghcjs/ghcjs/issues/529#issuecomment-252653274, but it's most probably an unrelated fluke of ghcjs.

**Comment by Mikolaj** [comment]
I've now also used nextAnimationFrame (pushed) and it works correctly and the frames even seem fast at the start, but then it bogs down, then speeds up, then bogs down again and on average it's down to 1.03 FPS (from 1.75 FPS), but now the frames seem 100% correct, no skipping, no shearing. So, AFAICS, the only remaining problem for me is the speed and memory consumption (especially on the native binary side, I'm not sure, but possibly using JS, as such, is not a blocker) resulting from my usage pattern.

**Comment by Mikolaj** [comment]
Thank you for all that. I'm closing the issue, since the main decision is about the Webkit2 API and AFAICS right now, no decision will make Webkit2 API usable for my natively compiled code anyway.
