### ISSUE TITLE
Migrate to WebKit2 API

### ISSUE THREAD

**Issue by k0ral** [gtk2hs/webkit#7]
The current constraint `pkgconfig-depends: webkitgtk-3.0 >= 1.8` corresponds to a WebKit1 API, which has been removed from the WebKitGTK+ release since the [2.6.*](http://webkitgtk.org/2014/09/24/webkitgtk2.6.0-released.html) series.
I realize this is probably a significant change, and I would be glad to help this transition, so please let me know if/how I can contribute.

**Comment by eallik** [comment]
It would be very nice to have WebKit2 API support, that way we could build against Homebrew's webkitgtk 2.10.4 formula not the old 2.4.9 (which is currently only in MacPorts but I'm working on the Homebrew 2.4.9 formula as we speak).

**Comment by eallik** [comment]
@k0ral by the way, I'm not 100% sure, but I think `webkitgtk3` does not compile against anything newer than 2.4.9 regardless of WebKit API version — see my comments in https://github.com/gtk2hs/webkit/issues/13: `webkitgtk3` requires `webkit/webkitversion.h` but that doesn't seem to be available on anything newer than `webkitgtk-2.4.9`; but I'd love to be corrected.

**Comment by jorsn** [comment]
@eallik @k0ral `webkit/webkitversion.h` is part of the WebKit1 API and is only for this reason not available on `webkitgtk` versions newer than 2.4.9. So the problem *is* the API version.

**Comment by Mikolaj** [comment]
I wonder if https://hackage.haskell.org/package/gi-webkit helps us in any way here?

**Comment by k0ral** [comment]
Among the `gi-*` family of generated bindings, there are actually 2 packages for webkitgtk: `gi-webkit` and `gi-webkit2`, which I assume are bindings for Webkit1 and WebKit2 APIs, respectively.
I guess efforts are being diverted to those new bindings, so it might not be worth keeping this issue opened.

**Comment by hamishmack** [comment]
Using the `gi-webkit2` package is the way to go for WebKit2 support.
